version: "3"
services: 
  java:
    build:
      dockerfile: ./app.dockerfile
      context: .
    container_name: desafiostoom
    ports:
      - "8080:8080"
    networks: 
      - production-network

networks: 
  production-network:
    driver: bridge